// This file was auto-generated by prisma-generator-typescript-interfaces

export enum RoleEnum {
  ADMIN = "ADMIN",
  PROFESSOR = "PROFESSOR",
  STUDENT = "STUDENT",
}

export enum SemesterEnum {
  I = "I",
  II = "II",
  III = "III",
  IV = "IV",
  V = "V",
  VI = "VI",
  VII = "VII",
  VIII = "VIII",
  IX = "IX",
  X = "X",
}

export enum ExamApplicationStatusEnum {
  APPLIED = "APPLIED",
  PASSED = "PASSED",
  FAILED = "FAILED",
}

export type Announcements = {
  id: number;
  authorId: number | null;
  title: string;
  description: string;
  createdAt: Date;
  updatedAt: Date;
  author?: User | null;
};

export type Code = {
  id: number;
  userId: number;
  value: string;
  createdAt: Date;
  updatedAt: Date;
  user?: User;
};

export type Course = {
  id: number;
  professorId: number | null;
  semester: SemesterEnum;
  index: string;
  name: string;
  espb: number;
  description: string;
  createdAt: Date;
  updatedAt: Date;
  courseMaterials?: CourseMaterial[];
  professor?: User | null;
  enrollments?: Enrollments[];
  examApplications?: ExamApplication[];
};

export type CourseMaterial = {
  id: number;
  courseId: number;
  title: string;
  description: string;
  filename: string;
  filepath: string;
  createdAt: Date;
  updatedAt: Date;
  course?: Course;
};

export type Enrollments = {
  id: number;
  studentId: number;
  courseId: number;
  course?: Course;
  student?: User;
};

export type ExamApplication = {
  id: number;
  examPeriodId: number;
  courseId: number;
  studentId: number;
  status: ExamApplicationStatusEnum;
  grade: number | null;
  gradedAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
  course?: Course;
  examPeriod?: ExamPeriod;
  student?: User;
};

export type ExamPeriod = {
  id: number;
  name: string;
  dateFrom: Date;
  dateTo: Date;
  createdAt: Date;
  updatedAt: Date;
  examApplications?: ExamApplication[];
};

export type PersonalAccessToken = {
  id: number;
  userId: number;
  token: string;
  lastUsedAt: Date;
  expiresAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
  user?: User;
};

export type User = {
  id: number;
  role: RoleEnum;
  index: string | null;
  email: string;
  firstName: string;
  lastName: string | null;
  parentName: string | null;
  address: string | null;
  phoneNumber: string | null;
  password: string;
  emailVerifiedAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
  announcements?: Announcements[];
  code?: Code | null;
  courses?: Course[];
  enrollments?: Enrollments[];
  examApplications?: ExamApplication[];
  tokens?: PersonalAccessToken[];
};
